export const Listserie = [
  {
    id: "ce4e47ae-5e0a-42c4-a61e-b0fb8d6c7b8b",
    nom: "Ozark",
    description:
      "Marty blanchit de l'argent pour le compte d'un baron de la drogue. Lorsque son partenaire le trahit, il déménage avec sa famille aux monts Ozarks. Là-bas, il se retrouve opposé à un dealer local, à une bande de voyous et à un agent du FBI tenace.s",
    image:
      "https://www.badtaste.co.kr/wp-content/uploads/2020/06/poster-780.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/pJlLLif3v9k",
    categorie: "Drame",
    star: "10/10",
    exit_date: "2017",
    realisateur: "/",
  },
  {
    id: "21200443-be36-4639-b890-c14ec10d4ad2",
    nom: "Breaking Bad",
    description:
      "Walter White, 50 ans, est professeur de chimie dans un lycée du Nouveau-Mexique. Pour réunir de l'argent afin de subvenir aux besoins de sa famille, Walter met ses connaissances en chimie à profit pour fabriquer et vendre du crystal meth.",
    image: "https://fr.web.img5.acsta.net/pictures/19/06/18/12/11/3956503.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/HynAYiKTAmc",
    categorie: "Action, Drame",
    star: "10/10",
    exit_date: "2008",
    realisateur: "Mark Johnson",
  },
  {
    id: "49c0d437-8650-4e5d-872d-6d9dedb2ca96",
    nom: "Better Call Saul",
    description:
      "Ce spin-off de la série `Breaking Bad' suit la vie de Jimmy McGill avant qu'il ne prenne le pseudonyme de Saul Goodman et devienne l'avocat véreux de Walter White.",
    image: "https://fr.web.img2.acsta.net/pictures/18/07/02/14/12/5660762.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/7ykFY6UPe98",
    categorie: "Action, Thriller",
    star: "10/10",
    exit_date: "2015",
    realisateur:
      "Bob Odenkirk; Nina Jack; Diane Mercer; Robin Sweet; Gordon Smith; Jonathan Glatzer",
  },
  {
    id: "e1a0a783-d7a5-463f-b3c2-9b6f27757bd7",
    nom: "Mr. Robot",
    description:
      "Elliot Alderson est un jeune informaticien vivant à New York, qui travaille en tant qu'ingénieur en sécurité informatique pour Allsafe Security. Celui-ci luttant constamment contre un trouble d'anxiété sociale et de dépression.",
    image:
      "https://1.bp.blogspot.com/-Fz1JwOjgFR4/XgKzkSjMhOI/AAAAAAABNnU/exXe5MrTYo82scS81VDo6_Tbuggf9S6EQCLcBGAsYHQ/s1600/mrrobot.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/mltyFW0tVvA",
    categorie: "Action, Thriller",
    star: "10/10",
    exit_date: "2015",
    realisateur: "Universal Cable Productions; Anonymous Content",
  },
  {
    id: "2ac9e0a8-673e-4469-a8db-a2406b8b6b8c",
    nom: "Gomorra",
    description:
      "En Italie, la famille Savastano, dirigée par l'impitoyable Don Pietro, domine la mafia napolitaine. En concurrence avec un autre clan de la Camorra, Don Pietro doit penser à préparer sa succession.",
    image: "https://fr.web.img4.acsta.net/pictures/18/11/07/16/53/5118969.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/pB6Mfu-87QI",
    categorie: "Action, Drame",
    star: "10/10",
    exit_date: "2014",
    realisateur: "Cattleya; Sky Italia",
  },
  {
    id: "e8143f40-5a46-4131-82fc-821275e60352",
    nom: "The Witcher",
    description:
      "Hexer Geralt reprend la mission inachevée d'un autre sorceleur dans un royaume traqué par une bête féroce. Yennefer se forge un avenir magique au prix d'un terrible sacrifice.",
    image: "https://fr.web.img6.acsta.net/pictures/19/12/12/12/13/2421997.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/ymYBUDq6wnI",
    categorie: "Action, Drame",
    star: "10/10",
    exit_date: "20 décembre 2019",
    realisateur:
      "Sean Daniel Company; Platige Image; Stillking Films; One of Us; Cinesite",
  },
  {
    id: "b659883e-e9b7-414d-94f4-7aaf4cee683e",
    nom: "Sons of Anarchy",
    description:
      "Pour protéger leur ville des dealers, les membres d'un club de motos sont prêts à tout.",
    image:
      "https://pictures.betaseries.com/fonds/poster/2c15c000bb11737b1523702b5fe1c5e0.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/eJXu1N_DC7E",
    categorie: "Action, Drame",
    star: "10/10",
    exit_date: "2008",
    realisateur: "Kurt Sutter; Art Linson; James D. Parriott",
  },
  {
    id: "bba175fa-09e4-48d3-a18d-0db9826c10ed",
    nom: "Elite",
    description:
      "Quand trois adolescents de la classe moyenne se retrouvent admis dans une prestigieuse école privée d'Espagne, les tensions entre eux et les élèves dégénèrent rapidement et se finissent en un meurtre.",
    image: "https://fr.web.img4.acsta.net/pictures/18/10/18/07/54/1893178.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/pr8gOKsF6ek",
    categorie: "Amour, Sex, Drame",
    star: "10/10",
    exit_date: "2018",
    realisateur: "",
  },
  {
    id: "7e6e58dc-b69d-4bfc-8b9d-b4e0e50c7617",
    nom: "Stranger Things",
    description:
      "En 1983, à Hawkins dans l'Indiana, Will Byers disparaît de son domicile. Ses amis se lancent alors dans une recherche semée d'embûches pour le retrouver. Pendant leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite.",
    image: "https://fr.web.img3.acsta.net/pictures/19/01/03/10/42/0987125.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/wQoHfKDncLU",
    categorie: "Action, Thriller",
    star: "10/10",
    exit_date: "2016",
    realisateur: "Millie Bobby Brown, Finn Wolfhard, Noah Schnapp, PLUS",
  },
  {
    id: "5a2eb5cc-94c5-440d-882e-db71060ecbb7",
    nom: "Damnation",
    description:
      "Seth Davenport est un homme se faisant passer pour un prédicateur dans une ville de l'Iowa dans l'espoir de déclencher une insurrection à part entière contre le statu quo. Il ignore qu'un magnat industriel a embauché un brise-grève professionnel.",
    image: "https://fr.web.img5.acsta.net/pictures/17/10/04/17/45/0690259.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/iBiAD4xjgsA",
    categorie: "Action, Drame",
    star: "9/10",
    exit_date: "2017",
    realisateur: "",
  },
  {
    id: "ea10e313-724b-4c27-85ad-b40c2ab86c82",
    nom: "The Last Kingdom",
    description:
      "Au IXe siècle, l'Angleterre, séparée en de nombreux royaumes, est envahie par les Vikings menés par le Roi Alfred. Alors que le royaume de Wessex est le seul à résister, Uhtred doit choisir entre son pays natal et le peuple qui l'a élevé.",
    image:
      "https://4.bp.blogspot.com/-qLgd-dYxVnk/W8MmK3mDJlI/AAAAAAABD_I/kFqjZPNqfg4DVCknSjLv2ACZuLjMAYZtwCLcBGAs/s1600/The%2BLast%2BKingdom%2B%25E2%2580%2593%2BSaison%2B2.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/KXu54ZIpTPg",
    categorie: "Histoire",
    star: "8/10",
    exit_date: "2015",
    realisateur: "",
  },
  {
    id: "a3d174c2-85dc-4e7d-9e57-5f0c45812380",
    nom: "Orange Is the New Black",
    description:
      "Piper est incarcérée à Litchfield pour quinze mois car elle a transporté une valise d'argent pour son amante, Alex Vause. Elle tente de se faire à la vie en prison, entre le clanisme, les réseaux et les fortes personnalités des autres détenues.",
    image: "https://fr.web.img3.acsta.net/pictures/18/07/11/09/42/3320480.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/lNvocVbXE_Y",
    categorie: "Drame",
    star: "10/10",
    exit_date: "2013",
    realisateur: "",
  },
  {
    id: "423eccfc-5e85-4a69-87a8-662ba3ccc1a1",
    nom: "Peaky Blinders",
    description:
      "Birmingham, en 1919. Un gang familial règne sur un quartier de la ville : les Peaky Blinders, ainsi nommés pour les lames de rasoir qu'ils cachent dans la visière de leur casquette.",
    image: "https://fr.web.img6.acsta.net/pictures/15/03/11/17/20/597260.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/OU1iZoOrkVo",
    categorie: "Drame",
    star: "10/10",
    exit_date: "2013",
    realisateur: "Katie Swinden",
  },
  {
    id: "3ef64f8c-43b1-4b18-a1d7-e07f0e1c78f0",
    nom: "La casa de papel",
    description:
      "Huit voleurs font une prise d'otages dans la Maison royale de la Monnaie d'Espagne, tandis qu'un génie du crime manipule la police pour mettre son plan à exécution.",
    image:
      "https://i.pinimg.com/originals/46/84/de/4684de7e080ee747bffbb5fedf43ede0.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/_yJxbWKN3zE",
    categorie: "Drame",
    star: "10/10",
    exit_date: "2017",
    realisateur: "",
  },
  {
    id: "535b62c5-6246-49f3-86b0-c7d02276aa4d",
    nom: "Homeland",
    description:
      "Après une confidence de l'un de ses informateurs, Carrie Mathison, agent de la CIA souffrant secrètement d'un trouble bipolaire, est la seule persuadée que Nicholas Brody, marine américain libéré lors d'une opération commando, est radicalisé.",
    image:
      "https://cache.marieclaire.fr/data/photo/w616_c17/homeland_tv_serie.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/f0YbEaJyAy8",
    categorie: "Action, Drame, Guerre",
    star: "10/10",
    exit_date: "2011",
    realisateur: "",
  },
  {
    id: "848eb1cf-5aca-4c9f-a113-9c5314b2d4fa",
    nom: "Van Helsing",
    description:
      "Vanessa Helsing, cousine éloignée d'un chasseur de vampires, émerge d'entre les morts pour apprendre que les buveurs de sang ont pris le contrôle du monde, et qu'elle représente le dernier espoir de l'Humanité.",
    image: "https://fr.web.img5.acsta.net/pictures/16/08/02/16/51/525667.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/ENy0AMGkbMs",
    categorie: "Drame",
    star: "8/10",
    exit_date: "2016",
    realisateur: "",
  },
  {
    id: "88c447f6-235e-405e-88db-65412d15e9ba",
    nom: "One Punch Man",
    description:
      "One Punch Man est un manga en ligne écrit et dessiné par ONE. Il est publié sur le site personnel de l'auteur depuis le 3 juin 2009. La série est devenue très populaire, dépassant les dix millions de visites avec une moyenne de 20 000 par jour.",
    image:
      "https://media.senscritique.com/media/000011636491/source_big/One_Punch_Man.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/U1EQ24xFyIM",
    categorie: "Série de mangas",
    star: "10/10",
    exit_date: " 3 juillet 2009",
    realisateur: "ONE",
  },
  {
    id: "bc8e3645-6908-45db-8403-a374ecfe89af",
    nom: "Les Chroniques de Shannara",
    description:
      "Trois héroines essayent de stopper une armée de démon de détruire le monde.",
    image:
      "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQuT-C0gW2mlbDwCdErgzlQJJ0CgbWfgnlYqcTAGpw8r4p8E_6u",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/mE2l7_N9r7s",
    categorie: "fantastique",
    star: "8/10",
    exit_date: "5 janvier 2016",
    realisateur: "",
  },
  {
    id: "15308103-4096-40d7-ad17-ad282d62fbe1",
    nom: "Frontier",
    description:
      "Declan Harp essaie d'obtenir une partie du marché de la fourrure au dix-huitième siècle. Le trappeur hors-la-loi mène une campagne pour briser le monopole de la Compagnie de la Baie d'Hudson sur la fourrure au Canada.",
    image:
      "https://i1.wp.com/courrierdefloride.com/wp-content/uploads/2018/01/frontier-affiche.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/QmuyuGPqXXQ",
    categorie: "Action, Aventure",
    star: "9/10",
    exit_date: "2016",
    realisateur: "",
  },
  {
    id: "efe4e5b1-2b6b-404e-b251-2d17bf3d1fd5",
    nom: "Good Girls",
    description:
      "Trois meilleurs amis se regroupent pour arrêter de jouer selon les règles et prendre le contrôle de leur vie. Elles tiennent une épicerie pour sauver leurs familles en difficulté mais du fait d'être novice, s'en tirer ne sera peut-être pas si facile.",
    image: "https://fr.web.img2.acsta.net/pictures/19/02/15/12/01/1201341.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/simHOxnCFZI",
    categorie: "Drame, Humour",
    star: "9/10",
    exit_date: "26 février 2018",
    realisateur: "",
  },

  {
    id: "d60c33e4-aa5d-438d-8829-4f23433e3ad9",
    nom: "Désenchantée",
    description:
      "Après avoir abordé les temps modernes avec 'Les Simpsons' et l'avenir avec 'Futurama', le producteur Matt Groening entre dans le passé avec 'Désenchantée'. La série d'animation destinée aux adultes se déroule dans le royaume en ruine de Dreamland.",
    image: "https://fr.web.img4.acsta.net/pictures/18/07/19/12/26/2242700.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/rbpqjEDfKs4",
    categorie: "Comédie",
    star: "10/10",
    exit_date: "17 août 2018",
    realisateur: "",
  },
  {
    id: "80b99ca6-7206-448b-90f4-42dd68bcd312",
    nom: "How to Sell Drugs Online",
    description:
      "Pour impressionner son ancienne petite amie, un ado ringard commence à vendre de la drogue en ligne depuis sa chambre, avant de devenir l'un des plus gros dealeurs d'Europe.",
    image: "https://fr.web.img3.acsta.net/pictures/19/05/27/11/50/5254042.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/2uvtTeUa3gQ",
    categorie: "Comédie dramatique",
    star: "10/10",
    exit_date: "31 mai 2019",
    realisateur: "",
  },
  {
    id: "8ebea1a9-bc8d-46aa-8a25-bc09e0c2f342",
    nom: "Bad Blood",
    description:
      "Le parrain de la mafia montréalaise, Vito Rizzuto, est libéré après avoir purgé 31 ans de prison pour son rôle dans un assassinat. Après sa libération, il entame une campagne de vengeance contre ceux qui ont anéanti sa famille et ses amis.",
    image:
      "https://media.senscritique.com/media/000018027329/source_big/Bad_Blood.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/DLq7pezZiT0",
    categorie: "Criminel",
    star: "10/10",
    exit_date: "21 septembre 2017",
    realisateur: "",
  },
  {
    id: "359c650b-40a4-4ebd-b42c-1cdeada4e8d2",
    nom: "The Punisher",
    description:
      "Après le massacre de toute sa famille, un ex-agent d'élite du FBI, que l'on disait mort dans le carnage, se lance dans une impitoyable vendetta. Seule la mort de ses ennemis pourra l'arrêter.",
    image: "https://fr.web.img4.acsta.net/pictures/17/07/18/12/32/313669.jpg",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/exyq-EDnbec",
    categorie: "Super-héros",
    star: "10/10",
    exit_date: "17 novembre 2017",
    realisateur: "",
  },
  {
    id: "bfc99863-599d-4820-8ff8-75897de0fed1",
    nom: "Undercover",
    description:
      "Ferry Bouman, producteur d'ecstasy, partage sa vie entre sa maison et sa cabane au camping. Un jour, un couple de policier sous couverture va venir s'installer dans une caravane voisine pour tenter de démanteler son trafic.",
    image: "https://imgsrc.cineserie.com/2019/02/1236049.jpg?ver=1",
    alt: "Image du film",
    youtube: "https://www.youtube.com/embed/Vt4qQiM2Ahk?start=2",
    categorie: "Drame",
    star: "10/10",
    exit_date: "2019",
    realisateur: "",
  },
  // {
  //   id: "",
  //   nom: "",
  //   description: "",
  //   image: "",
  //   alt: "Image du film",
  //   youtube: "https://www.youtube.com/embed/",
  //   categorie: "",
  //   star: "",
  //   exit_date: "",
  //   realisateur: "",
  // },
];
